[project]
name = "ops-fusion-hackathon"
version = "1.0.0"
requires-python = ">=3.11,<3.12"
dependencies = []

[tool.uv]
python = "3.11"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
